# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import showtimes_pb2 as showtimes__pb2


class ShowtimesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShowtimeByDate = channel.unary_unary(
                '/Showtimes/GetShowtimeByDate',
                request_serializer=showtimes__pb2.Date.SerializeToString,
                response_deserializer=showtimes__pb2.ShowtimeData.FromString,
                )
        self.GetShowtimes = channel.unary_stream(
                '/Showtimes/GetShowtimes',
                request_serializer=showtimes__pb2.Empty.SerializeToString,
                response_deserializer=showtimes__pb2.ShowtimeData.FromString,
                )


class ShowtimesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShowtimeByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShowtimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowtimesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShowtimeByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShowtimeByDate,
                    request_deserializer=showtimes__pb2.Date.FromString,
                    response_serializer=showtimes__pb2.ShowtimeData.SerializeToString,
            ),
            'GetShowtimes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShowtimes,
                    request_deserializer=showtimes__pb2.Empty.FromString,
                    response_serializer=showtimes__pb2.ShowtimeData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Showtimes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Showtimes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShowtimeByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Showtimes/GetShowtimeByDate',
            showtimes__pb2.Date.SerializeToString,
            showtimes__pb2.ShowtimeData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetShowtimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Showtimes/GetShowtimes',
            showtimes__pb2.Empty.SerializeToString,
            showtimes__pb2.ShowtimeData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
