# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='booking.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbooking.proto\"\x0e\n\x0c\x45mptyBooking\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\">\n\rSingleBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"w\n\rBookingObject\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12)\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x1a.BookingObject.BookingDate\x1a+\n\x0b\x42ookingDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t2\xa5\x01\n\x07\x42ooking\x12\x30\n\x0bGetBookings\x12\r.EmptyBooking\x1a\x0e.BookingObject\"\x00\x30\x01\x12\x30\n\x13GetBookingsByUserID\x12\x07.UserID\x1a\x0e.BookingObject\"\x00\x12\x36\n\x12\x41\x64\x64\x42ookingByUserID\x12\x0e.SingleBooking\x1a\x0e.BookingObject\"\x00\x62\x06proto3'
)




_EMPTYBOOKING = _descriptor.Descriptor(
  name='EmptyBooking',
  full_name='EmptyBooking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=31,
)


_USERID = _descriptor.Descriptor(
  name='UserID',
  full_name='UserID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=53,
)


_SINGLEBOOKING = _descriptor.Descriptor(
  name='SingleBooking',
  full_name='SingleBooking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='SingleBooking.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='SingleBooking.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movieid', full_name='SingleBooking.movieid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=117,
)


_BOOKINGOBJECT_BOOKINGDATE = _descriptor.Descriptor(
  name='BookingDate',
  full_name='BookingObject.BookingDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='BookingObject.BookingDate.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movies', full_name='BookingObject.BookingDate.movies', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=238,
)

_BOOKINGOBJECT = _descriptor.Descriptor(
  name='BookingObject',
  full_name='BookingObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='BookingObject.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dates', full_name='BookingObject.dates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOOKINGOBJECT_BOOKINGDATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=238,
)

_BOOKINGOBJECT_BOOKINGDATE.containing_type = _BOOKINGOBJECT
_BOOKINGOBJECT.fields_by_name['dates'].message_type = _BOOKINGOBJECT_BOOKINGDATE
DESCRIPTOR.message_types_by_name['EmptyBooking'] = _EMPTYBOOKING
DESCRIPTOR.message_types_by_name['UserID'] = _USERID
DESCRIPTOR.message_types_by_name['SingleBooking'] = _SINGLEBOOKING
DESCRIPTOR.message_types_by_name['BookingObject'] = _BOOKINGOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyBooking = _reflection.GeneratedProtocolMessageType('EmptyBooking', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:EmptyBooking)
  })
_sym_db.RegisterMessage(EmptyBooking)

UserID = _reflection.GeneratedProtocolMessageType('UserID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:UserID)
  })
_sym_db.RegisterMessage(UserID)

SingleBooking = _reflection.GeneratedProtocolMessageType('SingleBooking', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:SingleBooking)
  })
_sym_db.RegisterMessage(SingleBooking)

BookingObject = _reflection.GeneratedProtocolMessageType('BookingObject', (_message.Message,), {

  'BookingDate' : _reflection.GeneratedProtocolMessageType('BookingDate', (_message.Message,), {
    'DESCRIPTOR' : _BOOKINGOBJECT_BOOKINGDATE,
    '__module__' : 'booking_pb2'
    # @@protoc_insertion_point(class_scope:BookingObject.BookingDate)
    })
  ,
  'DESCRIPTOR' : _BOOKINGOBJECT,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingObject)
  })
_sym_db.RegisterMessage(BookingObject)
_sym_db.RegisterMessage(BookingObject.BookingDate)



_BOOKING = _descriptor.ServiceDescriptor(
  name='Booking',
  full_name='Booking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=241,
  serialized_end=406,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBookings',
    full_name='Booking.GetBookings',
    index=0,
    containing_service=None,
    input_type=_EMPTYBOOKING,
    output_type=_BOOKINGOBJECT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookingsByUserID',
    full_name='Booking.GetBookingsByUserID',
    index=1,
    containing_service=None,
    input_type=_USERID,
    output_type=_BOOKINGOBJECT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddBookingByUserID',
    full_name='Booking.AddBookingByUserID',
    index=2,
    containing_service=None,
    input_type=_SINGLEBOOKING,
    output_type=_BOOKINGOBJECT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKING)

DESCRIPTOR.services_by_name['Booking'] = _BOOKING

# @@protoc_insertion_point(module_scope)
