# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='showtime.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eshowtime.proto\"\x0f\n\rEmptySchedule\"\x19\n\tMovieDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\":\n\x0eScheduleObject\x12\x18\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\n.MovieDate\x12\x0e\n\x06movies\x18\x02 \x03(\t2p\n\x08Showtime\x12\x32\n\x0bGetSchedule\x12\x0e.EmptySchedule\x1a\x0f.ScheduleObject\"\x00\x30\x01\x12\x30\n\x0fGetMoviesByDate\x12\n.MovieDate\x1a\x0f.ScheduleObject\"\x00\x62\x06proto3'
)




_EMPTYSCHEDULE = _descriptor.Descriptor(
  name='EmptySchedule',
  full_name='EmptySchedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=33,
)


_MOVIEDATE = _descriptor.Descriptor(
  name='MovieDate',
  full_name='MovieDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='MovieDate.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=60,
)


_SCHEDULEOBJECT = _descriptor.Descriptor(
  name='ScheduleObject',
  full_name='ScheduleObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='ScheduleObject.date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movies', full_name='ScheduleObject.movies', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=120,
)

_SCHEDULEOBJECT.fields_by_name['date'].message_type = _MOVIEDATE
DESCRIPTOR.message_types_by_name['EmptySchedule'] = _EMPTYSCHEDULE
DESCRIPTOR.message_types_by_name['MovieDate'] = _MOVIEDATE
DESCRIPTOR.message_types_by_name['ScheduleObject'] = _SCHEDULEOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptySchedule = _reflection.GeneratedProtocolMessageType('EmptySchedule', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYSCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:EmptySchedule)
  })
_sym_db.RegisterMessage(EmptySchedule)

MovieDate = _reflection.GeneratedProtocolMessageType('MovieDate', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEDATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:MovieDate)
  })
_sym_db.RegisterMessage(MovieDate)

ScheduleObject = _reflection.GeneratedProtocolMessageType('ScheduleObject', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEOBJECT,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleObject)
  })
_sym_db.RegisterMessage(ScheduleObject)



_SHOWTIME = _descriptor.ServiceDescriptor(
  name='Showtime',
  full_name='Showtime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=122,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSchedule',
    full_name='Showtime.GetSchedule',
    index=0,
    containing_service=None,
    input_type=_EMPTYSCHEDULE,
    output_type=_SCHEDULEOBJECT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMoviesByDate',
    full_name='Showtime.GetMoviesByDate',
    index=1,
    containing_service=None,
    input_type=_MOVIEDATE,
    output_type=_SCHEDULEOBJECT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOWTIME)

DESCRIPTOR.services_by_name['Showtime'] = _SHOWTIME

# @@protoc_insertion_point(module_scope)
