# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bookings_pb2 as bookings__pb2


class BookingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookingByUserID = channel.unary_stream(
                '/Bookings/GetBookingByUserID',
                request_serializer=bookings__pb2.UserID.SerializeToString,
                response_deserializer=bookings__pb2.Date.FromString,
                )
        self.AddBookingByUserID = channel.unary_unary(
                '/Bookings/AddBookingByUserID',
                request_serializer=bookings__pb2.UserID.SerializeToString,
                response_deserializer=bookings__pb2.Result.FromString,
                )
        self.GetBookings = channel.unary_unary(
                '/Bookings/GetBookings',
                request_serializer=bookings__pb2.Empty.SerializeToString,
                response_deserializer=bookings__pb2.BookingObject.FromString,
                )


class BookingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookingByUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookingByUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookingByUserID': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBookingByUserID,
                    request_deserializer=bookings__pb2.UserID.FromString,
                    response_serializer=bookings__pb2.Date.SerializeToString,
            ),
            'AddBookingByUserID': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookingByUserID,
                    request_deserializer=bookings__pb2.UserID.FromString,
                    response_serializer=bookings__pb2.Result.SerializeToString,
            ),
            'GetBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookings,
                    request_deserializer=bookings__pb2.Empty.FromString,
                    response_serializer=bookings__pb2.BookingObject.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bookings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bookings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookingByUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Bookings/GetBookingByUserID',
            bookings__pb2.UserID.SerializeToString,
            bookings__pb2.Date.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBookingByUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bookings/AddBookingByUserID',
            bookings__pb2.UserID.SerializeToString,
            bookings__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bookings/GetBookings',
            bookings__pb2.Empty.SerializeToString,
            bookings__pb2.BookingObject.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
